version: '3.3'
services:
  php_posting:
    build:
      context: php_posting
      dockerfile: .docker/Dockerfile
    image: ${PHP_POSTING_IMAGE}
    container_name: ${PHP_POSTING_CONTAINER}
#    restart: always
    working_dir: /app
    environment:
      - APP_ENV=${PHP_ENVIRONMENT}
    volumes:
    - ./php_posting/src:/app
    ports:
    - 9000:9000
    networks:
    - bcnismagic_internal

  php_following:
    build:
      context: php_following
      dockerfile: .docker/Dockerfile
    image: ${PHP_FOLLOWING_IMAGE}
    container_name: ${PHP_FOLLOWING_CONTAINER}
#    restart: always
    working_dir: /app
    environment:
      - APP_ENV=${PHP_ENVIRONMENT}
    volumes:
      - ./php_following/src:/app
    ports:
      - 9001:9000
    networks:
      - bcnismagic_internal

  db_posting:
    image: postgres:11.4-alpine
    container_name: ${DB_POSTING_CONTAINER}
#    restart: always
    environment:
      POSTGRES_DB: ${DB_POSTING_DB}
      POSTGRES_USER: ${DB_POSTING_USER}
      POSTGRES_PASSWORD: ${DB_POSTING_PASSWORD}
      PGDATA: ${DB_POSTING_PGDATA}
    volumes:
    - ./db_posting/data:${DB_POSTING_PGDATA}
#    - postgres_data:${DB_POSTING_PGDATA}
    ports:
    - 5431:5432
    networks:
    - bcnismagic_internal
    - bcnismagic_external

  db_following:
    image: postgres:11.4-alpine
    container_name: ${DB_FOLLOWING_CONTAINER}
#    restart: always
    environment:
      POSTGRES_DB: ${DB_FOLLOWING_DB}
      POSTGRES_USER: ${DB_FOLLOWING_USER}
      POSTGRES_PASSWORD: ${DB_FOLLOWING_PASSWORD}
      PGDATA: ${DB_FOLLOWING_PGDATA}
    volumes:
      - ./db_following/data:${DB_FOLLOWING_PGDATA}
    ports:
      - 5432:5432
    networks:
      - bcnismagic_internal
      - bcnismagic_external

  metabase:
    image: metabase/metabase
    container_name: metabase
    environment:
      MB_DB_FILE: '/metabase.db'
    ports:
      - 3000:3000
    volumes:
      - ./metabase/data/metabase.db:/metabase.db
    networks:
      - bcnismagic_internal

#  search_following:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
#    container_name: ${SEARCH_FOLLOWING_CONTAINER}
#    environment:
#      - discovery.type=single-node
##    ulimits:
##      memlock:
##        soft: -1
##        hard: -1
#    volumes:
#      - ./search_following/data:${SEARCH_FOLLOWING_DATA}
##      - elasticsearch_data:${SEARCH_FOLLOWING_DATA}
#    ports:
#      - 9200:9200
#    networks:
#      - bcnismagic_internal
#      - bcnismagic_external

#volumes:
#  elasticsearch_data:
#    driver: local
#  postgres_data:
#    driver: local

networks:
  bcnismagic_internal:
    driver: bridge
  bcnismagic_external:
    external: true
