doctrine:
  dbal:
    driver: 'pdo_pgsql'
    server_version: '11'
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_unicode_ci
    url: '%env(DB_URL)%'

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Image:
        type: yml
        dir: '%kernel.project_dir%/config/doctrine/posting/domain/model/image'
        is_bundle: false
        prefix: App\Posting\Domain\Model\Image
        alias: Image
