App\Posting\Domain\Model\Image\Image:
  type: entity
  table: images
  id:
    id:
      type: guid
      generator:
        strategy: NONE
  fields:
    createdAt:
      type: datetime_immutable
      column: created_at
      nullable: false
    providerId:
      type: string
      column: provider_id
      nullable: false
    provider:
      type: string
      column: provider
      nullable: false
    providerUrl:
      type: string
      column: provider_url
      nullable: false
    path:
      type: string
      column: path
      nullable: true
    description:
      type: string
      column: description
      nullable: true
    location:
      type: string
      column: location
      nullable: true
    likes:
      type: integer
      nullable: false
      column: likes
    numberOfComments:
      type: integer
      nullable: false
      column: number_of_comments
    views:
      type: integer
      nullable: false
      column: views
    downloads:
      type: integer
      nullable: false
      column: downloads
    author:
      type: string
      column: author
      nullable: false
    tags:
      type: json_array
      column: tags
      nullable: true
    postedAt:
      type: datetime_immutable
      column: posted_at
      nullable: true
    isDiscarded:
      type: boolean
      nullable: true
      collumn: is_discarded
    caption:
      type: text
      nullable: true
    rate:
      type: float
      nullable: true

