parameters:
  ELASTICSEARCH_HOST: '%env(string:ELASTICSEARCH_HOST)%'
  ELASTICSEARCH_PORT: '%env(int:ELASTICSEARCH_PORT)%'
  IG_CONFIG:
    storage: file
    basefolder: '%kernel.project_dir%/var/ig/'
  IG_ACCOUNT: '%env(string:IG_ACCOUNT)%'
  IG_PASSWORD: '%env(string:IG_PASSWORD)%'
  IG_READ_ACCOUNT: '%env(string:IG_READ_ACCOUNT)%'
  IG_READ_PASSWORD: '%env(string:IG_READ_PASSWORD)%'
  FOLLOWER_SIZE: 10
