-- Deploy bcn_is_magic:20190709_1 to pg

BEGIN;

ALTER TABLE IMAGES ADD COLUMN posted_at TIMESTAMP DEFAULT NULL,
ADD COLUMN is_discarded BOOL DEFAULT NULL,
ADD COLUMN caption TEXT DEFAULT NULL,
ADD COLUMN rate FLOAT DEFAULT NULL;

COMMIT;
