parameters:
  DB_URL: '%env(string:DB_URL)%'
  UNSPLASH_SECRET_KEY: '%env(string:UNSPLASH_SECRET_KEY)%'
  UNSPLASH_ACCESS_KEY: '%env(string:UNSPLASH_ACCESS_KEY)%'
  UNSPLASH_APP_NAME: 'ig_posting'
  IMAGES_PATH: '%kernel.project_dir%/var/images/'
  REMOVE_IMAGES_ENABLED: '%env(bool:REMOVE_IMAGES_ENABLED)%'
  IG_CONFIG:
    storage: file
    basefolder: '%kernel.project_dir%/var/ig/'
  IG_ACCOUNT: '%env(string:IG_ACCOUNT)%'
  IG_PASSWORD: '%env(string:IG_PASSWORD)%'