imports:
  - { resource: parameters.yaml }

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: false      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  image_provider_unsplash:
    public: true
    class: App\Posting\Infrastructure\Api\Image\UnsplashImageProvider
    arguments:
      - '%UNSPLASH_ACCESS_KEY%'
      - '%UNSPLASH_SECRET_KEY%'
      - '%UNSPLASH_APP_NAME%'

  image_provider_pexels:
    public: true
    class: App\Posting\Infrastructure\Api\Image\PexelsImageProvider
    arguments:
      - '%PEXELS_ACCESS_KEY%'

  image_repository:
    public: true
    class: App\Posting\Infrastructure\Persistance\Doctrine\Image\DoctrineImageRepository
    arguments:
      - '@doctrine.orm.entity_manager'

  image_storage_file:
    public: true
    class: App\Posting\Infrastructure\File\Image\FileImageStorage
    arguments:
      - '%IMAGES_PATH%'
      - '%REMOVE_IMAGES_ENABLED%'

  image_storage_aws:
    public: true
    class: App\Posting\Infrastructure\Api\Image\AwsImageStorage
    arguments:
      - '%AWS_KEY%'
      - '%AWS_SECRET%'
      - '%AWS_BUCKET%'
      - '%AWS_REGION%'
      - '%IMAGES_PATH%'
      - '%REMOVE_IMAGES_ENABLED%'

  image_storage:
    public: true
    class: App\Posting\Infrastructure\Api\Image\AwsImageStorageContext
    arguments:
      - '@image_storage_file'
      - '@image_storage_aws'
      - '%env(APP_ENV)%'

  image_provider_factory:
    public: true
    class: App\Posting\Domain\Model\Image\ImageProviderFactory
    arguments:
      - '@image_provider_unsplash'
      - '@image_provider_pexels'

  images_recollect_by_term_from_unsplash:
    public: true
    class: App\Posting\Application\Service\Image\RecollectImagesByTermService
    arguments:
      - '@image_repository'
      - '@image_provider_factory'
      - '@image_storage'

  clean_images_service:
    public: true
    class: App\Posting\Application\Service\Image\CleanImagesService
    arguments:
      - '@image_repository'
      - '@image_storage'
      - '@tag_repository'

  image_recollect_command:
    public: true
    class: App\Posting\Infrastructure\Console\Command\Image\RecollectImagesCommand
    arguments:
      - '@images_recollect_by_term_from_unsplash'
    tags:
      - { name: 'console.command', command: 'recollect-images' }

  clean_images_command:
    public: true
    class: App\Posting\Infrastructure\Console\Command\Image\CleanImagesCommand
    arguments:
      - '@clean_images_service'
    tags:
      - { name: 'console.command', command: 'clean-images' }

  tag_repository:
    public: true
    class: App\Posting\Infrastructure\File\Tag\FileTagRepository

  post_image_adapter:
    public: true
    class: App\Posting\Infrastructure\Api\Image\IgPostImageAdapter
    arguments:
      - '%IG_CONFIG%'
      - '%env(APP_DEBUG)%'
      - '%env(APP_DEBUG)%'
      - '%IG_ACCOUNT%'
      - '%IG_PASSWORD%'
      - '%IMAGES_PATH%'

  caption_repository:
    class: App\Posting\Infrastructure\File\Caption\FileCaptionRepository
    public: true

  generate_image_caption_service:
    class: App\Posting\Application\Service\Image\GenerateImageCaptionService
    public: true
    arguments:
      - '@image_repository'
      - '@caption_repository'
      - '@tag_repository'

  post_image_service:
    class: App\Posting\Application\Service\Image\PostImageService
    public: true
    arguments:
      - '@post_image_adapter'
      - '@image_repository'
      - '@generate_image_caption_service'

  post_image_command:
    public: true
    class: App\Posting\Infrastructure\Console\Command\Image\PostImageCommand
    arguments:
      - '@post_image_service'
      - '@image_repository'
    tags:
      - { name: 'console.command', command: 'post-image' }